service: webb

provider:
  name: aws
  role: arn:aws:iam::992382436111:role/LabRole
  runtime: nodejs18.x
  region: us-east-1
  environment:
    DB_HOST: ${env:DB_HOST, 'localhost'}
    DB_USER: ${env:DB_USER, 'ionic'}
    DB_PASSWORD: ${env:DB_PASSWORD, 'Larsi@123456'}
    DB_NAME: ${env:DB_NAME, 'bbdd_web'}
    DB_PORT: ${env:DB_PORT, '3306'}
  httpApi:
    cors:
      allowedOrigins:
        - "*"
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowedHeaders:
        - "*"
  logs:
    httpApi: true

plugins:
  - serverless-offline

functions:
  api:
    handler: handler.main
    events:
      - httpApi:
          path: /{proxy+}
          method: any
      - httpApi:
          path: /
          method: any
